[package]
name = "rustplayground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
itertools = "0.12.0"
z3 = "0.12.1"

[[bin]]
name = "rustplayground"
path = "main.rs"
